enum BackendOperation {
  openCollection(1),
  closeCollection(2),
  deckTree(3),
  setCurrentDeck(4),
  getQueuedCards(5),
  describeNextStates(6),
  answerCard(7),
  stateIsLeech(8),
  buryOrSuspendCards(9),
  getUndoStatus(10),
  undo(11),
  renderExistingCard(12),
  extractAvTags(13),
  allTtsVoices(14),
  writeTtsStream(15),
  getDeckConfigsForUpdate(16),
  encodeIriPaths(17),
  renameDeck(18),
  removeDecks(19),
  getNotetypeNamesAndCounts(20),
  newNote(21),
  addNote(22),
  getNotetype(23),
  defaultsForAdding(24),
  searchCards(25),
  browserRowForId(26),
  setActiveBrowserColumns(27),
  getConfigJson(28),
  getNote(29),
  updateNotes(30),
  getCard(31),
  removeCards(32),
  allBrowserColumns(33),
  newDeck(34),
  addDeck(35),
  updateNotetype(36),
  addNotetype(37),
  removeNotetype(38);

  const BackendOperation(this.nativeId);
  final int nativeId;
}
