use anki_flutter_bridge::operations::{
    ABORT_MEDIA_SYNC, ABORT_SYNC, ADD_DECK, ADD_MEDIA_FILE, ADD_MEDIA_FROM_URL, ADD_NOTETYPE,
    ALL_BROWSER_COLUMNS, ALL_TTS_VOICES, ANSWER_CARD, BURY_OR_SUSPEND_CARDS, CHECK_MEDIA,
    CLOSE_COLLECTION, CUSTOM_STUDY, CUSTOM_STUDY_DEFAULTS, DECK_TREE, DESCRIBE_NEXT_STATES,
    ENCODE_IRI_PATHS, EXPORT_ANKI_PACKAGE, EXTRACT_AV_TAGS, FULL_UPLOAD_OR_DOWNLOAD,
    GET_ABSOLUTE_MEDIA_PATH, GET_CONFIG_STRING, GET_DECK_CONFIGS_FOR_UPDATE,
    GET_IMPORT_ANKI_PACKAGE_PRESETS, GET_QUEUED_CARDS, GET_UNDO_STATUS, IMPORT_ANKI_PACKAGE,
    MEDIA_SYNC_STATUS, NEW_DECK, OPEN_COLLECTION, REMOVE_CARDS, REMOVE_NOTES, REMOVE_NOTETYPE,
    RENDER_EXISTING_CARD, RESTORE_TRASH, SCHEDULE_CARDS_AS_NEW, SCHEDULE_CARDS_AS_NEW_DEFAULTS, SET_CURRENT_DECK,
    SET_CUSTOM_CERTIFICATE, SET_DUE_DATE, STATE_IS_LEECH, SYNC_COLLECTION, SYNC_LOGIN, SYNC_MEDIA,
    SYNC_STATUS, TRASH_MEDIA_FILES, UNBURY_DECK, UNDO, UPDATE_DECK_CONFIGS, UPDATE_NOTETYPE, WRITE_TTS_STREAM,
};

#[test]
fn required_operations_are_distinct_and_available() {
    let values = [
        OPEN_COLLECTION,
        CLOSE_COLLECTION,
        DECK_TREE,
        SET_CURRENT_DECK,
        GET_QUEUED_CARDS,
        DESCRIBE_NEXT_STATES,
        ANSWER_CARD,
        STATE_IS_LEECH,
        BURY_OR_SUSPEND_CARDS,
        GET_UNDO_STATUS,
        UNDO,
        RENDER_EXISTING_CARD,
        EXTRACT_AV_TAGS,
        ALL_TTS_VOICES,
        WRITE_TTS_STREAM,
        GET_DECK_CONFIGS_FOR_UPDATE,
        ENCODE_IRI_PATHS,
        REMOVE_CARDS,
        REMOVE_NOTES,
        ALL_BROWSER_COLUMNS,
        NEW_DECK,
        ADD_DECK,
        UPDATE_NOTETYPE,
        ADD_NOTETYPE,
        REMOVE_NOTETYPE,
        GET_IMPORT_ANKI_PACKAGE_PRESETS,
        IMPORT_ANKI_PACKAGE,
        EXPORT_ANKI_PACKAGE,
        CUSTOM_STUDY_DEFAULTS,
        CUSTOM_STUDY,
        UNBURY_DECK,
        UPDATE_DECK_CONFIGS,
        SYNC_LOGIN,
        SYNC_STATUS,
        SYNC_COLLECTION,
        FULL_UPLOAD_OR_DOWNLOAD,
        SYNC_MEDIA,
        MEDIA_SYNC_STATUS,
        ABORT_SYNC,
        ABORT_MEDIA_SYNC,
        SET_CUSTOM_CERTIFICATE,
        ADD_MEDIA_FILE,
        ADD_MEDIA_FROM_URL,
        CHECK_MEDIA,
        GET_ABSOLUTE_MEDIA_PATH,
        TRASH_MEDIA_FILES,
        RESTORE_TRASH,
        SCHEDULE_CARDS_AS_NEW,
        SCHEDULE_CARDS_AS_NEW_DEFAULTS,
        GET_CONFIG_STRING,
        SET_DUE_DATE,
    ];

    assert_eq!(values.len(), 51);
    for (index, left) in values.iter().enumerate() {
        for right in values.iter().skip(index + 1) {
            assert_ne!(left, right);
        }
    }
}
