use anki_flutter_bridge::operations::{
    ADD_DECK, ADD_NOTETYPE, ALL_BROWSER_COLUMNS, ALL_TTS_VOICES, ANSWER_CARD,
    BURY_OR_SUSPEND_CARDS, CLOSE_COLLECTION, CUSTOM_STUDY, CUSTOM_STUDY_DEFAULTS, DECK_TREE,
    DESCRIBE_NEXT_STATES, ENCODE_IRI_PATHS, EXPORT_ANKI_PACKAGE, EXTRACT_AV_TAGS,
    GET_DECK_CONFIGS_FOR_UPDATE, GET_IMPORT_ANKI_PACKAGE_PRESETS, GET_QUEUED_CARDS,
    GET_UNDO_STATUS, IMPORT_ANKI_PACKAGE, NEW_DECK, OPEN_COLLECTION, REMOVE_CARDS,
    REMOVE_NOTETYPE, RENDER_EXISTING_CARD, SET_CURRENT_DECK, STATE_IS_LEECH, UNBURY_DECK,
    UNDO, UPDATE_NOTETYPE, WRITE_TTS_STREAM,
};

#[test]
fn required_operations_are_distinct_and_available() {
    let values = [
        OPEN_COLLECTION,
        CLOSE_COLLECTION,
        DECK_TREE,
        SET_CURRENT_DECK,
        GET_QUEUED_CARDS,
        DESCRIBE_NEXT_STATES,
        ANSWER_CARD,
        STATE_IS_LEECH,
        BURY_OR_SUSPEND_CARDS,
        GET_UNDO_STATUS,
        UNDO,
        RENDER_EXISTING_CARD,
        EXTRACT_AV_TAGS,
        ALL_TTS_VOICES,
        WRITE_TTS_STREAM,
        GET_DECK_CONFIGS_FOR_UPDATE,
        ENCODE_IRI_PATHS,
        REMOVE_CARDS,
        ALL_BROWSER_COLUMNS,
        NEW_DECK,
        ADD_DECK,
        UPDATE_NOTETYPE,
        ADD_NOTETYPE,
        REMOVE_NOTETYPE,
        GET_IMPORT_ANKI_PACKAGE_PRESETS,
        IMPORT_ANKI_PACKAGE,
        EXPORT_ANKI_PACKAGE,
        CUSTOM_STUDY_DEFAULTS,
        CUSTOM_STUDY,
        UNBURY_DECK,
    ];

    assert_eq!(values.len(), 30);
    for (index, left) in values.iter().enumerate() {
        for right in values.iter().skip(index + 1) {
            assert_ne!(left, right);
        }
    }
}
